# Generated by Django 3.2.2 on 2021-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='coverimage',
            field=models.ImageField(default=None, upload_to=None),
            preserve_default=False,
        ),
    ]
