# Generated by Django 3.2.2 on 2021-05-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_posts_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='editor.profiles'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='coverimage',
            field=models.ImageField(upload_to='media'),
        ),
    ]
